spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.104:3306/sell?verifyServerCertificate=false&useSSL=false&requireSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
logging:
  pattern:
    console: "%d - %msg%n"
